version: "3"

services:
  mockbin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      MOCKBIN_REDIS: "redis://redis:6379"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: sh -c "sysctl vm.overcommit_memory=1 && redis-server"
    privileged: true
